version: '3'

services:
    bot:
        image: b89ede331e28
        env_file: .env-bot
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - quotly
        command: node index.js
        volumes:
            - ./config:/app/config
    mongo:
        restart: always
        image: mongo
        volumes:
            - ./data/db:/data/db
        ports:
            - 127.0.0.1:27017:27017
        networks:
            - quotly
    api:
        image: 6e4733a6b16f
        env_file: .env-api
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - ./fonts:/usr/share/fonts
        networks:
            - quotly
        command: node index.js

networks:
    quotly:
        